### ISSUE TITLE
How to add more comments to the 3 provided?

### ISSUE THREAD

**Issue by MrSassyBritches** [clutcher/comments_highlighter#1]
Would like to add other triggers like + or other symbols

**Comment by clutcher** [comment]
So you want to have possibility to add user defined symbols? I'll take a look, but don't think that I'll have  enough time to do that.

**Comment by melMass** [comment]
What is the point of the addon without that feature?

**Comment by clutcher** [comment]
I made some initial implementation in CH-1 branch for that. You can play around with it if you wish.

Unfortunately I found unexpected behavior in intellij idea in color settings refresh. I opened a bug (https://youtrack.jetbrains.com/issue/IDEA-226087), hope they will fix it fast. Don't want to publish new plugin version with this bug.

**Comment by clutcher** [comment]
Implemented in release 1.3 (https://github.com/clutcher/comments_highlighter/releases/tag/1.3)
