### ISSUE TITLE
Custom-Folding Coloring Option  

### ISSUE THREAD

**Issue by Redevectored** [clutcher/comments_highlighter#10]
Hello!
Is there a way to only re-color the custom-fold regions ("Description" in the picture), but not any other folds like the comment blocks?

Thank you a lot for the add-on and your quick previous responses to issues. 

![image](https://user-images.githubusercontent.com/57843146/92458486-beca4600-f1c5-11ea-8e85-9a7c60eb28f9.png)

**Comment by clutcher** [comment]
Hi, @Redevectored . Sorry, I  didn't get the issue. Can you also add source code without folding?

**Comment by Redevectored** [comment]
Thank you for the quick reply. Here is the un-folded source code. 
To describe the issue further: Is there a way to give the two (differently) folded code-blocks different colors? 
![image](https://user-images.githubusercontent.com/57843146/92909992-f0dae280-f427-11ea-921f-db3f4f4052f1.png)

**Comment by clutcher** [comment]
This plugin doesn't change color of collapse folded block. It is changing color for comments/part of comments only.
