### ISSUE TITLE
Add support of Lexer based highlighting, which is used in Rider to highlight C++ files

### ISSUE THREAD

**Issue by hwooo** [clutcher/comments_highlighter#11]
![2021-02-01](https://user-images.githubusercontent.com/46282492/106391360-4728dc00-6430-11eb-99de-1089c7ea8999.png)

There is no highlighting if I write comments in Rider for UE.

**Comment by clutcher** [comment]
Unfortunately I can't find Rider for Unreal Engine version for Linux to debug your issue.

**Comment by clutcher** [comment]
There is Win and Mac versions, but still waiting for Linux version to be released.

**Comment by neelkoos** [comment]
The Linux version was released! I hope you able to fix it now.

**Comment by clutcher** [comment]
@hwooo @neelkoos Looks good on my side. Can you share your example, which I can use for tests?

![2021-12-17_11-03-48](https://user-images.githubusercontent.com/5013860/146518464-c63c6339-dff3-4df8-b52c-f0b2587182ea.png)

**Comment by neelkoos** [comment]
It works with .cs but .cpp and .h not.

![image](https://user-images.githubusercontent.com/59707920/146521055-9f8b5117-f630-4606-adac-c2b4d0ab63fd.png)

**Comment by clutcher** [comment]
@neelkoos Thanks. 

That highlighting is special one (it is basic lexer highlighting) and it doesn't support intellij annotators, which I use for additional highlighting. I'll work on it next but it will take some time to understand how to extend that highlighting and override it.

**Comment by clutcher** [comment]
Intermediate results of investigation:

EditorImpl has list of change listeners, which we execute one by one. One of the listener is LexerEditorHighlighter, which holds CppLexer inside. After execution of this listener and lexer we can get from LexerEditorHighlighter data about token types and text of token. 

In theory we can write and add one more listener, which will check find that highlighter, extract token types and text, process with comment highlighter and override TextAttribute.

P.S.
Get token type by segment index:
((LexerEditorHighlighter) listeners[20]).getSegments().unpackTokenFromData(((LexerEditorHighlighter) listeners[20]).getSegments().getSegmentData(0))


Get token text by segment index:
this.getImmutableCharSequence().subSequence(((LexerEditorHighlighter) listeners[20]).getSegments().getSegmentStart(0),((LexerEditorHighlighter) listeners[20]).getSegments().getSegmentEnd(0))
