### ISSUE TITLE
[PHPStorm] Highlighting does not work for phpdocs within a class

### ISSUE THREAD

**Issue by ditsuke** [clutcher/comments_highlighter#28]
It looks like while highlighting is working for phpdocs, it fails for phpdocs that are within a class.

![image](https://user-images.githubusercontent.com/72784348/126315397-cd68e569-0884-4f30-ac6e-fe70e7f6ec28.png)

**Comment by clutcher** [comment]
@ditsuke Looks good on latest intellij:

![2021-07-20_18-35-32](https://user-images.githubusercontent.com/5013860/126353185-acd99a1f-b93c-4f20-9e62-adef56e07bfb.png)

Are you on latest version?

**Comment by ditsuke** [comment]
> Are you on latest version?

@clutcher Yes, I'm on the latest PHPStorm and Comment Highlighter, installed fresh from the marketplace.

**Comment by clutcher** [comment]
@ditsuke Checked on fresh PHPStorm with latest plugin version, looks good. Maybe some other plugin is causing that? Can you send a list of enabled plugins?

**Comment by ditsuke** [comment]
@clutcher 

* [List of enabled plugins (paste.mozilla.com)](https://paste.mozilla.org/0BRAezv3)
* [TestCommentHighlighter.php.zip](https://github.com/clutcher/comments_highlighter/files/6849924/TestCommentHighlighter.zip)

![image](https://user-images.githubusercontent.com/72784348/126362748-74428af2-551c-4871-9a3d-75fd352d7fc3.png)

**Comment by ditsuke** [comment]
It looks like the issue is with indented comments in general. It doesn't matter if they're outside a class:

![image](https://user-images.githubusercontent.com/72784348/126363927-500c4ecf-9bda-4103-ad70-0951f67704e9.png)

**Comment by clutcher** [comment]
@ditsuke Was able to reproduce with your test file. Issue is that PHP doc comment in that case uses a special PhpDocToken instead of generic PsiComment. I'll work on it and prepare a new version in nearest few days.

P.S. Thanks for creating github ticket for that bug.

**Comment by clutcher** [comment]
Fix would be released in next few days
