### ISSUE TITLE
Support Webstorm EAP 2020.1

### ISSUE THREAD

**Issue by Talaar** [clutcher/comments_highlighter#3]
First, great job and many thx for the plugin.

Is it possible that the plugin also supports webstream EAP 2020.1 because the plugin is removed in the eap because of unsupported version.

**Comment by clutcher** [comment]
Thanks. I'll check what's wrong.

**Comment by clutcher** [comment]
Uploaded version with fix on Jetbrains marketplace. Till Tuesday it should reach general availability.

**Comment by clutcher** [comment]
@Talaar Updated version with EAP support reach general availability.
