### ISSUE TITLE
Highlighting Twig and Blade comments in PHPStorm are not working

### ISSUE THREAD

**Issue by clutcher** [clutcher/comments_highlighter#36]
From Flavien Grevillot:

I installed your great plugin Comment Highlighter on PhpStorm and I was wondering if the support of Twig comment {# #} is something I can setup on my side or if it’s something you need to add ? I ask because I saw 'Commented lines highlighting is supported for any language’ in the doc but it is not working when I use Twig comments in Twig files.

**Comment by Flvn404** [comment]
@clutcher I'm using PhpStorm 2021.2 and Twig template language support is bundled into PhpStorm so I'm not using extra plugin to highlight Twig syntax

FYI, I also tried into Blade template (.blade.php files with {{--    --}} comments delimiter and same issue on my side). Blade template language support is bundled into PhpStorm too.
