### ISSUE TITLE
Tokens made from series of special characters doesn't work

### ISSUE THREAD

**Issue by dadiborn** [clutcher/comments_highlighter#39]
I wanted to make three comment tokens using '&gt;' character like so:
- [x] &gt;
- [x] &gt;&gt;
- [x] &gt;&gt;&gt;

Worked only solo version, two+ accepted but doesn't set/change any color in comments section of my TypeScript file.

P.S. And Huge Thanks for continuing to support this plugin and making fantastic improvements in it!

**Comment by iMobCoding** [comment]
+1 for this one

Maybe add one more type like COMMENT KEYWORD so when you parse comments you first search for keywords (by removing all white spaces after the comment and checking for starting keyword) and if that fails you proceed with regular COMMENT parsing. Maybe that wouldn't degrade performance so much?

**Comment by clutcher** [comment]
Found a way to deal with that. On configuration saving we will persist tokens sorted by length desc. 

After plugin update you would need to modify token list, so the configuration would be saved with sorting.

![2021-11-29_11-40-19](https://user-images.githubusercontent.com/5013860/143845653-59640702-2ef6-4284-ae5b-7997a211ee78.png)
