### ISSUE TITLE
keywords don't works on IntelliJ IDEA 2021.3

### ISSUE THREAD

**Issue by gungun974** [clutcher/comments_highlighter#41]
Hello, maybe I am wrong in my use of the plugin but despite trying to reproduce as on the screenshots I cannot change the color of a keyword (here "plublic")
I tested this under Linux then under MacOS but no difference. 
![Screen Shot 2021-12-13 at 21 31 30](https://user-images.githubusercontent.com/5224459/145860832-59241e43-1f69-475d-8631-bf041e549cfe.png)

**Comment by clutcher** [comment]
@gungun974 Can you check what type of keyword is "public"? If it is "METHOD KEYWORD", then highlight would be applied to class methods only. To highlight any "public" keyword, including on class level (your screenshot) you should change type to just "KEYWORD". You can check that in Settings->Editor->Comment Highlighter.

**Comment by gungun974** [comment]
Thanks @clutcher, I'm sorry to answer that now to say that I had misread the documentation :sweat_smile:.
In short, the custom syntax highlighting now works in Java.
