### ISSUE TITLE
true, false, null keywords highlighting doesn't work.

### ISSUE THREAD

**Issue by ErioGH** [clutcher/comments_highlighter#42]
Hello, when i'm trying to change highlighting for these keywords, there is no any effect. 
For other keywords everything works properly. Am I doing something wrong?
![highlighting doesn't work](https://user-images.githubusercontent.com/41791932/146687158-ee8a9109-ae24-480e-9728-8e35f110acee.jpg)

**Comment by clutcher** [comment]
@ErioGH true, false and null are not keywords.They are regular literals. I can check if idea add some metadata, which I can use to identify this values.

**Comment by ErioGH** [comment]
When i'm trying to edit colour scheme, there is no true or false in the example text, but they definitely inherit they colour scheme from keyword type, also as null. 
<img width="1246" alt="Screenshot 2021-12-20 at 23 31 30" src="https://user-images.githubusercontent.com/41791932/146830468-1a1c7d11-561a-4bbb-b812-c04c5f9cd747.png">

**Comment by ErioGH** [comment]
this option is available in Material Theme UI, but it was locked by paywall since recently, so a think Idea has some metadata.
<img width="1280" alt="Screenshot 2021-12-20 at 23 48 28" src="https://user-images.githubusercontent.com/41791932/146832118-d754b4ac-a415-48c1-ae05-c05d4cbf2692.png">

**Comment by clutcher** [comment]
@ErioGH 

Material Theme greatly extends existing Intellij possibilities including highlights, so it is not relevant to compare with it. 
Also I checked that Idea provides metadata, which I can use to add support for such type of tokens.
