### ISSUE TITLE
Add support for Javascript keyword highlighting

### ISSUE THREAD

**Issue by gungun974** [clutcher/comments_highlighter#45]
Hello, I wanted to know if it was normal for this extension that I can't seem to change the color of a keyword ("public" in this example) in a Typescript file (".ts") or in a JavaScript file (".js").
(Yes I know that the public keyword does not exist in Javascript).
![Screen Shot 2021-12-29 at 22 01 28](https://user-images.githubusercontent.com/5224459/147691094-d9cf1d04-1376-4851-b19a-706bf81bb959.png)

**Comment by clutcher** [comment]
@gungun974 Coloring you can change in Editor -> Color Scheme -> Comments/Keywords

![2021-12-31_12-44-07](https://user-images.githubusercontent.com/5013860/147819040-da85fded-f9c1-4b05-812c-48cd193b4183.png)

**Comment by clutcher** [comment]
Also if it is not a language keyword - it wouln not be highlighted. Plugin works only for keywords and comments, not for any word in a text file.

**Comment by gungun974** [comment]
**_Happy new years !_** 

So i already change color foreground in the comment / keywords color scheme.
It's work in Java, the "public" keyword change color but in JavaScript (".js") when i try with "var" keyword, it's does nothing. (And worst the color change of "var" work in Java files)
I am sure it's a kind of bug or something missing in this plugin cause i will be very unlike that the JavaScript keyword "var" is not really a keyword for Jetbrain...

Maybe the answer to this is to create a `JavaScriptKeywordHighlighterAnnotator.java` and `TypeScriptKeywordHighlighterAnnotator.java` like you do for "PHP, CPP, C, C# Java and Koltin" but i know nothing about Jetbrain plugin development and how really work your plugin (Otherwise I would have tried something on my side and I would have already made a pull request).

**Comment by Jimmy-JS** [comment]
Hi! sorry but I still has some problem with some of javascript syntax which I tried to change `async` and `await` syntax in javascript.

Here is my setting:
![image](https://user-images.githubusercontent.com/9798426/187861050-f3f2cb4f-b1b9-4377-96e9-40faa77938f0.png)
![image](https://user-images.githubusercontent.com/9798426/187861100-4a1b5f83-c799-4938-bd0c-3c31a7138e6a.png)

Result:
![image](https://user-images.githubusercontent.com/9798426/187861683-0eb7ffcc-34d1-4a26-af07-fac72a0db844.png)

As you can see, I'm trying to change `await`, `async`, and `let` color to light blue. for `let` it's working properly. but it doesn't change the color of the `async` and `await` and it still use the IDE javascript keyword color which is purple (is it because of the prioritization?). any work around for this?

Thanks before!

**Comment by gungun974** [comment]
> Hi @clutcher, sorry but I still has some problem with some of javascript syntax which I tried to change `async` and `await` syntax in javascript.
> 
> Here is my setting: ![image](https://user-images.githubusercontent.com/9798426/187861050-f3f2cb4f-b1b9-4377-96e9-40faa77938f0.png) ![image](https://user-images.githubusercontent.com/9798426/187861100-4a1b5f83-c799-4938-bd0c-3c31a7138e6a.png)
> 
> Result: ![image](https://user-images.githubusercontent.com/9798426/187861683-0eb7ffcc-34d1-4a26-af07-fac72a0db844.png)
> 
> As you can see, I'm trying to change `await`, `async`, and `let` color to light blue. for `let` it's working properly. but it doesn't change the color of the `async` and `await` and it still use the IDE javascript keyword color which is purple (is it because of the prioritization?). any work around for this?
> 
> Thanks before!

Hello. 
I can confirm I got the same result and the worst it's I never realized my "await" and "async" are in wrongs colors before.

I don't thinks it's not possible to fix this since already all other keywords works correctly. (I suppose cause I never change all keywords of colors...)

One thing you can try @Jimmy-JS  is to change globally the JavaScript keyword color and then change every other keyword with your colors.

Just to finish I want to say this plugin is for me the best Plugin I can see on Idea and I'm glad to have make it's work for JS & TS cause it's just a pleasure to work with it.
