### ISSUE TITLE
Not working with rider 

### ISSUE THREAD

**Issue by ArKeid0s** [clutcher/comments_highlighter#47]
Hi as you can see on the screenshot the plugin is not working on rider 
![image](https://user-images.githubusercontent.com/46865726/151016139-f5d5f8bd-0c53-422e-95b0-63a84fc91493.png)

I hope you can fix that
Thanks

**Comment by clutcher** [comment]
@ArKeid0s Screenshot looks good. Can you provide more info?

**Comment by Ares9323** [comment]
I'm not the author of this issu but I confirm it's not working for me in Rider 2022.1 with C++
It's working only inside comments:
![image](https://user-images.githubusercontent.com/46932745/166744686-d13fb664-2941-4808-b2cd-c641c10e1856.png)

The "public" METHOD_KEYWORD is the plugin default and it's not working too (All colors are set, also tried setting background color thinking that they were overridden by the theme but nothing changes)

**Comment by clutcher** [comment]
@Ares9323 Can you send me file, where highlights are not working for you? I still can't reproduce it. And what OS you are using?

**Comment by Ares9323** [comment]
> @Ares9323 Can you send me file, where highlights are not working for you? I still can't reproduce it. And what OS you are using?
Sure, it doesn't work in any file created with Unreal Engine, so I'll send you two random files:
[DragonExcavator.zip](https://github.com/clutcher/comments_highlighter/files/8630273/DragonExcavator.zip)

Edition	Windows 10 Pro
Version	21H2
Installed on	‎12/‎03/‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by clutcher** [comment]
@Ares9323 I'm on Linux on Intellij 2021.1.3.

FRotaror is not an keyword, so it is not highlighting. Everything else is working as expected:

![2022-05-05_22-28-49](https://user-images.githubusercontent.com/5013860/167020484-91e7ba51-d26c-4d58-b877-44b1bce9b50c.png)

![2022-05-05_22-31-33](https://user-images.githubusercontent.com/5013860/167020584-e29b3bb1-d5c3-4c45-9c87-fdbac850e799.png)


But I noticed that Intellij itself is lagging, so I need to cut public section in .h file and undo the cut to fix highlighting. And I just noticed that on your screenshot is .txt file, they support only comments for highlighting and could be buggy. Not sure what else I can check or do.

**Comment by clutcher** [comment]
@Ares9323 The more I'm looking into that the more I think that is is issue with rendering inside intellij itself.

**Comment by Ares9323** [comment]
Sorry, I haven't had time to answer yesterday! Thank you for the support.

> FRotaror is not an keyword, so it is not highlighting. 

Sorry again, it's a variable type (and it's recognized by Rider since it reads the engine source code) so I thought it was considered as a "keyword", I also thought I could highlight any word (in vscode I use regex to do that) but apparently I'm wrong!

Also the macro UPROPERTY and UFUNCTION should be recognized as keywords.

It there's anything I could do to help you just ask, I'm also available for a remote session if you need

Do you have any tip or workaround?

**Comment by clutcher** [comment]
Don't think that I can do anything with that. I will load a ticket to do some generic regexp highlighting disabled by default to not impact performance #55 .
