### ISSUE TITLE
For Rider 2022.3.1 Does not work with CS files

### ISSUE THREAD

**Issue by Chris85hh** [clutcher/comments_highlighter#50]
in Rider it does not work with all cs files. 
but when I open a TS file it uses the correct settings.

![image](https://user-images.githubusercontent.com/27524484/209005935-9da607cc-2f34-42e6-8d92-ee58973b1275.png)

**Comment by clutcher** [comment]
Looks like I need to update plugin to Java 17.

**Comment by clutcher** [comment]
@Chris85hh Please recheck with latest plugin version (2.5), should become available in a day or so on marketplace.

**Comment by Chris85hh** [comment]
Thanks, as soon as it is available I test it and give feedback here

**Comment by Chris85hh** [comment]
@clutcher I updated it and the error is there just as before.
in TypeScrip files it works fine and in CS files the keyword are not highlighted. 
if i can provide any logs or an example project to help feel free to contact me

**Comment by clutcher** [comment]
@clutcher Can you send file and keyword, which is not working, please.

**Comment by Chris85hh** [comment]
@clutcher here are the files if something is missing let me know, thanks
![keyword](https://user-images.githubusercontent.com/27524484/212976528-f35881cf-dd75-4c3d-99c5-5cedef26c3b1.png)
![fileView](https://user-images.githubusercontent.com/27524484/212976544-3a7f6610-ef92-4370-9c16-20e3f7666218.png)
[ConsoleApp1.zip](https://github.com/clutcher/comments_highlighter/files/10438113/ConsoleApp1.zip)

**Comment by Chris85hh** [comment]
@clutcher Thank you, with the version 2.5.1 it works perfectly.
